//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "adjudicator_availability_override")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub adjudicator_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub round_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::adjudicator::Entity",
        from = "Column::AdjudicatorId",
        to = "super::adjudicator::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Adjudicator,
    #[sea_orm(
        belongs_to = "super::tournament_round::Entity",
        from = "Column::RoundId",
        to = "super::tournament_round::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TournamentRound,
}

impl Related<super::adjudicator::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Adjudicator.def()
    }
}

impl Related<super::tournament_round::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TournamentRound.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
