//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "adjudicator")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub chair_skill: i16,
    pub panel_skill: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::adjudicator_availability_override::Entity")]
    AdjudicatorAvailabilityOverride,
    #[sea_orm(has_many = "super::ballot_adjudicator::Entity")]
    BallotAdjudicator,
    #[sea_orm(
        belongs_to = "super::participant::Entity",
        from = "Column::Uuid",
        to = "super::participant::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Participant,
    #[sea_orm(has_many = "super::tournament_break_adjudicator::Entity")]
    TournamentBreakAdjudicator,
}

impl Related<super::adjudicator_availability_override::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdjudicatorAvailabilityOverride.def()
    }
}

impl Related<super::ballot_adjudicator::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BallotAdjudicator.def()
    }
}

impl Related<super::participant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Participant.def()
    }
}

impl Related<super::tournament_break_adjudicator::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TournamentBreakAdjudicator.def()
    }
}

impl Related<super::ballot::Entity> for Entity {
    fn to() -> RelationDef {
        super::ballot_adjudicator::Relation::Ballot.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::ballot_adjudicator::Relation::Adjudicator.def().rev())
    }
}

impl Related<super::tournament_break::Entity> for Entity {
    fn to() -> RelationDef {
        super::tournament_break_adjudicator::Relation::TournamentBreak.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::tournament_break_adjudicator::Relation::Adjudicator
                .def()
                .rev(),
        )
    }
}

impl Related<super::tournament_round::Entity> for Entity {
    fn to() -> RelationDef {
        super::adjudicator_availability_override::Relation::TournamentRound.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::adjudicator_availability_override::Relation::Adjudicator
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
