//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ballot_speech_timing")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub speech_ballot_id: Uuid,
    pub speech_role: String,
    pub speech_position: i32,
    pub start_time: Option<DateTime>,
    pub end_time: Option<DateTime>,
    pub response_start_time: Option<DateTime>,
    pub response_end_time: Option<DateTime>,
    pub pause_milliseconds: i32,
    pub response_pause_milliseconds: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ballot_speech::Entity",
        from = "(Column::SpeechBallotId, Column::SpeechBallotId, Column::SpeechBallotId, Column::SpeechRole, Column::SpeechRole, Column::SpeechRole, Column::SpeechPosition, Column::SpeechPosition, Column::SpeechPosition)",
        to = "(super::ballot_speech::Column::Role, super::ballot_speech::Column::BallotId, super::ballot_speech::Column::Position, super::ballot_speech::Column::BallotId, super::ballot_speech::Column::Position, super::ballot_speech::Column::Role, super::ballot_speech::Column::BallotId, super::ballot_speech::Column::Role, super::ballot_speech::Column::Position)",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BallotSpeech,
}

impl Related<super::ballot_speech::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BallotSpeech.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
