//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "institution_alias")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub institution: Uuid,
    #[sea_orm(unique)]
    pub alias: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::well_known_institution::Entity",
        from = "Column::Institution",
        to = "super::well_known_institution::Column::Uuid",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WellKnownInstitution,
}

impl Related<super::well_known_institution::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WellKnownInstitution.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
