//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub mod prelude;

pub mod adjudicator;
pub mod adjudicator_availability_override;
pub mod ballot_adjudicator;
pub mod debate_backup_ballot;
pub mod feedback_form;
pub mod feedback_form_question;
pub mod feedback_question;
pub mod feedback_response;
pub mod feedback_response_value;
pub mod participant_clash;
pub mod participant_tournament_institution;
pub mod speaker;
pub mod team;
pub mod tournament;
pub mod tournament_break;
pub mod tournament_break_adjudicator;
pub mod tournament_break_speaker;
pub mod tournament_break_team;
pub mod tournament_debate;
pub mod tournament_institution;
pub mod tournament_log;
pub mod tournament_plan_edge;
pub mod tournament_plan_node;
pub mod tournament_plan_node_round;
pub mod tournament_remote;
pub mod tournament_round;
pub mod tournament_venue;
pub mod user;
pub mod user_access_key;
pub mod user_participant;
pub mod user_tournament;
use super::manual::*;
