//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0-rc.2

pub use super::adjudicator::Entity as Adjudicator;
pub use super::ballot_adjudicator::Entity as BallotAdjudicator;
pub use super::participant::Entity as Participant;
pub use super::speaker::Entity as Speaker;
pub use super::team::Entity as Team;
pub use super::tournament::Entity as Tournament;
pub use super::tournament_debate::Entity as TournamentDebate;
pub use super::tournament_log::Entity as TournamentLog;
pub use super::tournament_remote::Entity as TournamentRemote;
pub use super::tournament_round::Entity as TournamentRound;
