//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "published_tournament")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub tournament_id: Option<Uuid>,
    pub public_name: String,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub image_data: Option<Vec<u8>>,
    pub image_type: Option<String>,
    pub list_publicly: bool,
    pub show_motions: bool,
    pub show_draws: bool,
    pub show_tab: bool,
    pub start_date: Option<DateTime>,
    pub end_date: Option<DateTime>,
    pub location: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
