//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "speaker")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub team_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::participant::Entity",
        from = "Column::Uuid",
        to = "super::participant::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Participant,
    #[sea_orm(
        belongs_to = "super::team::Entity",
        from = "Column::TeamId",
        to = "super::team::Column::Uuid",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Team,
    #[sea_orm(has_many = "super::tournament_break_speaker::Entity")]
    TournamentBreakSpeaker,
}

impl Related<super::participant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Participant.def()
    }
}

impl Related<super::team::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Team.def()
    }
}

impl Related<super::tournament_break_speaker::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TournamentBreakSpeaker.def()
    }
}

impl Related<super::tournament_break::Entity> for Entity {
    fn to() -> RelationDef {
        super::tournament_break_speaker::Relation::TournamentBreak.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::tournament_break_speaker::Relation::Speaker
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
