//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0-rc.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "team")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub name: String,
    pub tournament_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::feedback_response::Entity")]
    FeedbackResponse,
    #[sea_orm(has_many = "super::speaker::Entity")]
    Speaker,
    #[sea_orm(
        belongs_to = "super::tournament::Entity",
        from = "Column::TournamentId",
        to = "super::tournament::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tournament,
}

impl Related<super::feedback_response::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FeedbackResponse.def()
    }
}

impl Related<super::speaker::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Speaker.def()
    }
}

impl Related<super::tournament::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tournament.def()
    }
}

impl Related<super::tournament_break::Entity> for Entity {
    fn to() -> RelationDef {
        super::tournament_break_team::Relation::TournamentBreak.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::tournament_break_team::Relation::Team.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
