//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tournament_break_category")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub name: String,
    pub tournament_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tournament::Entity",
        from = "Column::TournamentId",
        to = "super::tournament::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tournament,
    #[sea_orm(has_many = "super::tournament_break_eligible_category::Entity")]
    TournamentBreakEligibleCategory,
}

impl Related<super::tournament::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tournament.def()
    }
}

impl Related<super::tournament_break_eligible_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TournamentBreakEligibleCategory.def()
    }
}

impl Related<super::tournament_plan_node::Entity> for Entity {
    fn to() -> RelationDef {
        super::tournament_break_eligible_category::Relation::TournamentPlanNode.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::tournament_break_eligible_category::Relation::TournamentBreakCategory
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
