//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tournament_break_adjudicator")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tournament_break_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub adjudicator_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::adjudicator::Entity",
        from = "Column::AdjudicatorId",
        to = "super::adjudicator::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Adjudicator,
    #[sea_orm(
        belongs_to = "super::tournament_break::Entity",
        from = "Column::TournamentBreakId",
        to = "super::tournament_break::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TournamentBreak,
}

impl Related<super::adjudicator::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Adjudicator.def()
    }
}

impl Related<super::tournament_break::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TournamentBreak.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
