//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tournament_plan_edge")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uuid: Uuid,
    pub source_id: Uuid,
    #[sea_orm(unique)]
    pub target_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tournament_plan_node::Entity",
        from = "Column::SourceId",
        to = "super::tournament_plan_node::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TournamentPlanNode2,
    #[sea_orm(
        belongs_to = "super::tournament_plan_node::Entity",
        from = "Column::TargetId",
        to = "super::tournament_plan_node::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TournamentPlanNode1,
}

impl ActiveModelBehavior for ActiveModel {}
