//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0-rc.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tournament_break_source_round")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tournament_break_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub tournament_round_id: Uuid,
    pub dependency_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tournament_break::Entity",
        from = "Column::TournamentBreakId",
        to = "super::tournament_break::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TournamentBreak,
    #[sea_orm(
        belongs_to = "super::tournament_round::Entity",
        from = "Column::TournamentRoundId",
        to = "super::tournament_round::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    TournamentRound,
}

impl Related<super::tournament_break::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TournamentBreak.def()
    }
}

impl Related<super::tournament_round::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TournamentRound.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
