//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0-rc.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ballot_speech")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub ballot_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub position: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub role: String,
    pub speaker_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::ballot::Entity",
        from = "Column::BallotId",
        to = "super::ballot::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Ballot,
    #[sea_orm(
        belongs_to = "super::speaker::Entity",
        from = "Column::SpeakerId",
        to = "super::speaker::Column::Uuid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Speaker,
    #[sea_orm(has_many="super::adjudicator_speech_score::Entity")]
    AdjudicatorSpeechScore,
}


impl Related<super::adjudicator_speech_score::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdjudicatorSpeechScore.def()
    }
}

impl Related<super::ballot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Ballot.def()
    }
}

impl Related<super::speaker::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Speaker.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
