name: Server

on:
  push:
    tags:
      - 'v*'
      - 'server-v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:
  build-api:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: "Some release"
        tag_name: ${{ github.ref_name }}
        repo: https://github.com/julmaxi/open_tab_server_releases
      env:
        GITHUB_TOKEN: ${{ secrets.SERVER_RELEASE_REPO_KEY }}