name: Server

on:
  push:
    tags:
      - 'v*'
      - 'server-v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:
  build-api:
    runs-on: ubuntu-24.04
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Rust setup
      uses: dtolnay/rust-toolchain@stable

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('./Cargo.lock') }}
    - name: Build API
      run: cd open_tab_server && cargo build --release; cd ..
    
    - name: Install frontend dependencies
      working-directory: 'participant_frontend'
      run: npm install
    
    - name: Build frontend
      working-directory: 'participant_frontend'
      run: npm run build
    
    - name: Bundle
      run: |
        mkdir open_tab_server_release
        mkdir open_tab_server_release/bin
        cp target/release/open_tab_server open_tab_server_release/bin
        cp -r participant_frontend/build open_tab_server_release/frontend_build
        cp -r open_tab_server/data open_tab_server_release/data
        zip -r open_tab_server.zip open_tab_server_release
        rm -r open_tab_server_release

    - name: Create Release
      id: create_release
      run: |
        gh release create ${{ github.ref_name }} open_tab_server.zip -R https://github.com/julmaxi/open_tab_server_releases
      env:
        GH_TOKEN: ${{ secrets.SERVER_RELEASE_REPO_KEY }}