name: Server

on:
  push:
    tags:
      - 'v*'
      - 'server-v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:
  build-api:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Create Release
      id: create_release
      run: |
        gh release create v0.0.1 -R https://github.com/julmaxi/open_tab_server_releases
      env:
        GH_TOKEN: ${{ secrets.SERVER_RELEASE_REPO_KEY }}